### ISSUE TITLE
命令行中无法使用input

### ISSUE THREAD

**Issue by yulk** [skywind3000/PyStand#26]
F:\SMALL\PyStand-py38>Hello from F:\SMALL\PyStand-py38\PyStand.int

Traceback (most recent call last):
  File "<string>", line 34, in <module>
  File "F:\SMALL\PyStand-py38\PyStand.int", line 10, in <module>
    filename = input("请输入EXCEL文件名（带后缀,EXCEL文件放在本文件同目录)")
RuntimeError: input(): lost sys.stdin

**Comment by yulk** [comment]
修改CMakeLists.txt：

> option(PYSTAND_CONSOLE "Build PyStand as a console application." ON)

自行编译的版本可以。希望下次release的时候直接发个控制台的版本。

> F:\SMALL\PyStand-py38>PyStand.exe
> Hello from F:\SMALL\PyStand-py38\PyStand.int
> 请输入EXCEL文件名（带后缀,EXCEL文件放在本文件同目录)hello.txt
> F:\SMALL\PyStand-py38\runtime\python38.zip
> F:\SMALL\PyStand-py38\runtime
> F:\SMALL\PyStand-py38
> F:\SMALL\PyStand-py38\site-packages

**Comment by skywind3000** [comment]
不用修改，cmake 初始化时加上：

    -DPYSTAND_CONSOLE=ON

即可
