### ISSUE TITLE
生成的.egg放在PyStand-py38-pyqt5文件下了，也添加了路径，删除python的script文件，报错如何更改？

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [skywind3000/PyStand#5]
源文件拷贝到script文件中没有问题。生成egg文件有问题了。
setup.py脚本
```
from setuptools import setup, find_packages

setup(
    name="script",
    version="0.1",
    packages=find_packages()
)

```
生成的文件名为script-0.1-py3.8.egg，拷贝到PyStand-py38-pyqt5中，显示
```
D:\aaa\PyStand-py38-pyqt5>Traceback (most recent call last):
  File "<string>", line 29, in <module>
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'main'
```

**Comment by wangwenqiangGitHub** [comment]
PyStand.int也修改了sys.path.append(os.path.abspath('script-0.1-py3.8.egg'))

**Comment by skywind3000** [comment]
注意打包以后，压缩包内的相对文件名不能是

script/main.pyc

而要是

main.pyc

才行。

**Comment by wangwenqiangGitHub** [comment]
> 

![image](https://user-images.githubusercontent.com/28779327/155287996-9ee21907-8bbb-487c-8aa7-ae05913444b5.png)
生成的egg文件如何查看是相对文件名的

**Comment by wangwenqiangGitHub** [comment]
![image](https://user-images.githubusercontent.com/28779327/155288576-397f5239-7dab-4f81-a59d-927cb8b3e069.png)
这个工程就是测试一下，不删除python文件没问题，删除python文件就打不开了

**Comment by wangwenqiangGitHub** [comment]
> 注意打包以后，压缩包内的相对文件名不能是
> 
> ```
> script/main.pyc
> ```
> 
> 而要是
> 
> ```
> main.pyc
> ```
> 
> 才行。

我看了一下，我的setup.py是在script里面的，运行后只有dist中的.egg文件，build中的是空的

**Comment by wangwenqiangGitHub** [comment]
![image](https://user-images.githubusercontent.com/28779327/155310135-b1f62ac5-637a-49bb-b872-88bf3201898e.png)

**Comment by skywind3000** [comment]
就你最后一张图看起来，egg 包里根本没有任何 py/pyc 文件啊。

不要用 setup 生成了，你自己 zip 一下，改个后缀名。

**Comment by wangwenqiangGitHub** [comment]
> 

嗯嗯，自己zip一下就可以了，感谢，接着探索一下加密的方式

**Comment by wangwenqiangGitHub** [comment]
> 就你最后一张图看起来，egg 包里根本没有任何 py/pyc 文件啊。
> 
> 不要用 setup 生成了，你自己 zip 一下，改个后缀名。

嗯嗯，自己zip一下就可以了，感谢，接着探索一下加密的方式

**Comment by skywind3000** [comment]
做过但是属于内部代码，不方便分享，开源的实现有空了再说吧。

**Comment by wangwenqiangGitHub** [comment]
> 

ok,  没作过加密的这种操作，感觉根据提供的思路上手还是有难度，期待有开源的方法，可以学习一下，也是非常感谢能有这个工程，将我的python的程序减小了好几倍体积

**Comment by wangwenqiangGitHub** [comment]
> 做过但是属于内部代码，不方便分享，开源的实现有空了再说吧。

ok, 根据加密思路自己实现还是有难度，之前没有接触过加密这种操作，也想学习一下，期待开源的项目，感谢这么好的工程，我的python的程序减小了几倍体积，非常赞

**Comment by zuowanbushiwo** [comment]
@wangwenqiangGitHub  能指导一下 怎么pyc egg打包吗？我把py 文件删除后，保留pyc，运行就报这个错。想做一下简单的加密。谢谢！
```
    import main
ModuleNotFoundError: No module named 'main'
```
