### ISSUE TITLE
numpy导入问题补录

### ISSUE THREAD

**Issue by whitecateattea** [skywind3000/PyStand#62]
之前在导入numpy出现问题时出现如下问题
![image](https://github.com/skywind3000/PyStand/assets/84962783/a74723e0-6a72-410e-87ea-010fa398e2ef)
需要检查一下原因：python小更新版本，之前出现问题是由于python是3.10.5，而下载的python embed版本是3.10.xx（忘了是多少了，但是不是0.5），必须版本严格一致。
还有anaconda中packages也有可能出现问题。

**Comment by skywind3000** [comment]
thanks

**Comment by ziwend** [comment]
same issue, not version related

PyStand-py38-x64\site-packages\numpy\core\__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.12 from "D:\Downloads\PyStand-py38-x64\PyStand.exe"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: DLL load failed while importing _multiarray_umath: 找不到指定的模块。


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 39, in <module>
  File "D:\Downloads\PyStand-py38-x64\PyStand.int", line 14, in <module>
    from example import start
  File "D:\Downloads\PyStand-py38-x64\example.py", line 1, in <module>
    import numpy as np
  File "D:\Downloads\PyStand-py38-x64\site-packages\numpy\__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
